repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Using a recent tag for stability
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 24.3.0 # Pinned version instead of stable
    hooks:
      - id: black
        # Using .flake8 config for line length (120)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0 # Using a recent tag for stability
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=120"] # Ensure compatibility with black and line length
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0 # Using a recent tag for stability
    hooks:
      - id: flake8
        args: ["--config=.flake8"] # Explicitly use our config file
